[package]
name = "ssv-fast"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
sha256-force-soft = ["sha2/force-soft"]

[dependencies]
blake3.workspace = true
sha2.workspace = true
ssv-canonical = { path = "../ssv-canonical" }
ssv-problem = { path = "../ssv-problem" }
ssv-service-protocol = { path = "../ssv-service-protocol" }
ssv-solution = { path = "../ssv-solution" }
ssv-validation = { path = "../ssv-validation" }
thiserror.workspace = true

[dev-dependencies]
ssv-relation = { path = "../ssv-relation" }
